name: Temporary Publish to PyPI

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine
    - name: Clean old builds
      run: |
        rm -rf dist/ build/ *.egg-info/
    - name: Build package
      run: python setup.py sdist bdist_wheel
    - name: List built files
      run: ls -la dist/
    - name: Check package metadata
      run: |
        tar -tzf dist/*.tar.gz | grep METADATA || echo "No METADATA found"
    - name: Publish to PyPI with API Token
      run: |
        twine upload dist/* --verbose --username __token__ --password $PYPI_TOKEN
      env:
        PYPI_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
